services:
  redis:
    build:
      context: ./redis
    volumes:
      - ./app/src/tls:/etc/redis/tls
      - ./app/src/redis-server/redis.conf:/etc/redis/redis.conf
    restart: always
    
  app:
    build:
      context: ./app
    restart: always
    volumes: 
      - ./app/src/tls:/app/tls
    depends_on:
      - redis
    
  nginx:
    build:
      context: ./nginx
    ports:
      - "8089:8089"
    volumes:
      - ./app/src/nginx-config:/etc/nginx/
    restart: always
    depends_on:
      - app