version: "3.8"
services:
  redis:
    build:
      context: ./redis
    volumes:
      - ./app/src/tls:/etc/redis/tls
      - ./app/src/redis-server/redis.conf:/etc/redis/redis.conf
      - ./app/src/redis-server/acl.conf:/etc/redis/acl.conf
      - ./app/src/redis-server/data:/data
    restart: always
    
  app:
    build:
      context: ./app
    restart: "no"
    volumes: 
      - ./app/src/tls:/app/tls
      - ./app/src/cmd/config.yaml:/app/config.yaml
    depends_on:
      - redis
    
  nginx:
    build:
      context: ./nginx
    ports:
      - "8089:8089"
    volumes:
      - ./app/src/nginx-config/nginx.conf:/etc/nginx/nginx.conf
    restart: "no"
    depends_on:
      - app
